Repository arcaneframework/arcanefem, pull requests merged in 2023-05, with the labels that each got.

#61 copy elastodynamics to soildynamics
  CMakeLists.txt
  soildynamics/CMakeLists.txt
  soildynamics/Fem.axl
  soildynamics/FemModule.cc
  soildynamics/Readme.md
  soildynamics/Soildynamics.config
  soildynamics/Test.Soildynamics.arc
  soildynamics/main.cc
Labels: reorg

#60 Traction via CaseTable
  elastodynamics/CMakeLists.txt
  elastodynamics/Fem.axl
  elastodynamics/FemModule.cc
  elastodynamics/Test.Elastodynamics.transient-traction.arc
  elastodynamics/traction_bar_test_1.txt
Labels: enhancement

#64 Paraxial bc
  meshes/msh/semi-circle-soil.geo
  meshes/msh/semi-circle-soil.msh
  soildynamics/FemModule.cc
Labels: novelty

#72 meshes for electrostatics
  meshes/msh/box-rod-circle.geo
  meshes/msh/box-rod-circle.msh
  meshes/msh/box-rods.geo
  meshes/msh/box-rods.msh
Labels: enhancement

#78 Fix some memory leaks in AlephDoFLinearSystem
  femutils/AlephDoFLinearSystem.cc
Labels: bug

#79 Allow support to re-use the matrix layout between solver calls
  femutils/AlephDoFLinearSystem.cc
  femutils/DoFLinearSystem.cc
  femutils/DoFLinearSystem.h
  soildynamics/FemModule.cc
Labels: enhancement
