Repository arcaneframework/arcanefem, pull requests merged in 2024-10, with the labels that each got.

#165 feat[poisson]: Support 3D mesh with COO and COO Sort
  femutils/CooFormatMatrix.h
  poisson/CMakeLists.txt
  poisson/CooBiliAssembly.cc
  poisson/CooSortBiliAssembly.cc
  poisson/FemModule.cc
  poisson/FemModule.h
  poisson/Test.L-shape.2D.coo-sort.arc
  poisson/Test.L-shape.2D.coo.arc
  poisson/Test.L-shape.3D.coo-sort.arc
  poisson/Test.L-shape.3D.coo.arc
Labels: enhancement

#169 Update image used by CIs and update GH Actions used
  .github/workflows/acoustics.yml
  .github/workflows/aerodynamics.yml
  .github/workflows/bilaplacian.yml
  .github/workflows/elasticity.yml
  .github/workflows/elastodynamics.yml
  .github/workflows/electrostatics.yml
  .github/workflows/fourier.yml
  .github/workflows/heat.yml
  .github/workflows/laplace.yml
  .github/workflows/passmo.yml
  .github/workflows/poisson.yml
  .github/workflows/soildynamics.yml
  .github/workflows/tests.yml
Labels: CI

#170 Add a workflow for Codecov
  .github/codecov.yml
  .github/workflows/codecov.yml
Labels: CI

#173 test[poisson]: Add missing multi-proc tests
  poisson/CMakeLists.txt
  poisson/Test.L-shape.2D.nwcsr.arc
  poisson/Test.L-shape.3D.nwcsr.arc
  poisson/Test.sphere.3D.csr-gpu.arc
Labels: test

#178 Build CSR matrix on GPU
  poisson/CMakeLists.txt
  poisson/CsrGpuBiliAssembly.cc
  poisson/FemModule.h
  poisson/Test.L-shape.2D.csr-gpu.arc
  poisson/Test.sphere.3D.csr-gpu.no-edge.arc
Labels: enhancement
