Repository arcaneframework/arcanefem, pull requests merged in 2024-03, with the labels that each got.

#134 [elasticity] Revert to use a 'Real3' instead of 'Real2' for node solution variable
  elasticity/Fem.axl
  elasticity/FemModule.cc
  elasticity/tests/test_elasticity_results.txt
Labels: bug

#133 Improve and fix Soil-dynamics
  soildynamics/CMakeLists.txt
  soildynamics/FemModule.cc
  soildynamics/Test.Soildynamics.arc
  soildynamics/Test.double-couple.paraxial.soil.arc
  soildynamics/tests/test_soildynamics_results.txt
Labels: bug, enhancement, test

#136 Add optional minimum value for test case comparison
  elasticity/CMakeLists.txt
  elasticity/FemModule.cc
  femutils/FemUtils.cc
  femutils/FemUtils.h
Labels: enhancement

#137 Fix compilation with Hypre 2.18 (for ubuntu 20.04)
  femutils/HypreDoFLinearSystem.cc
Labels: build

#138 Fix compilation with Hypre 2.14.
  femutils/HypreDoFLinearSystem.cc
Labels: build
