Repository arcaneframework/arcanefem, pull requests merged in 2024-01, with the labels that each got.

#94 Add support for GPU backend of Hypre
  femutils/AlephDoFLinearSystem.cc
  femutils/DoFLinearSystem.cc
  femutils/DoFLinearSystem.h
  femutils/HypreDoFLinearSystem.cc
  poisson/CMakeLists.txt
  poisson/FemModule.cc
Labels: enhancement, novelty

#95 Add parallel support for direct hypre backend
  femutils/CsrFormatMatrix.cc
  femutils/HypreDoFLinearSystem.cc
  poisson/CMakeLists.txt
  poisson/Test.poisson.hypre_direct.arc
Labels: enhancement, novelty

#96 Add timers for linear system solving
  femutils/HypreDoFLinearSystem.cc
  poisson/FemModule.cc
Labels: enhancement

#97 Load Arcane package in root file and remove sub-projects
  CMakeLists.txt
  aerodynamics/CMakeLists.txt
  elasticity/CMakeLists.txt
  elastodynamics/CMakeLists.txt
  electrostatics/CMakeLists.txt
  femutils/CMakeLists.txt
  fourier/CMakeLists.txt
  heat/CMakeLists.txt
  laplace/CMakeLists.txt
  passmo/CMakeLists.txt
  poisson/CMakeLists.txt
  soildynamics/CMakeLists.txt
Labels: enhancement

#99 Fix configuration when accelerator is enabled.
  CMakeLists.txt
  poisson/CMakeLists.txt
Labels: bug

#104 Use 'HYPRE_SetSpGemmUseVendor()' only for hypre version 2.27 and greater
  femutils/HypreDoFLinearSystem.cc
Labels: bug

#105 Use the rank of the sub-domain for output filename.
  poisson/FemModule.cc
  poisson/FemModule.h
Labels: bug

#106 Remove use of NodeLinearSystem.
  femutils/AlephNodeLinearSystem.cc
  femutils/CMakeLists.txt
  femutils/NodeLinearSystem.cc
  femutils/NodeLinearSystem.h
Labels: reorg

#110 run tests only if PETSc is present #109
  aerodynamics/CMakeLists.txt
  bilaplacian/CMakeLists.txt
  elasticity/CMakeLists.txt
  elastodynamics/CMakeLists.txt
  electrostatics/CMakeLists.txt
  fourier/CMakeLists.txt
  heat/CMakeLists.txt
  laplace/CMakeLists.txt
  poisson/CMakeLists.txt
  soildynamics/CMakeLists.txt
Labels: bug
