Repository arcaneframework/arcanefem, pull requests merged in 2024-02, with the labels that each got.

#118 Fix minor configuration problems
  femutils/CMakeLists.txt
  poisson/CMakeLists.txt
  poisson/CusparseBiliAssembly.hxx
  poisson/FemModule.cc
Labels: bug, enhancement

#120 Refactor to use source files instead of header files.
  poisson/BlCsrBiliAssembly.cc
  poisson/CMakeLists.txt
  poisson/CooBiliAssembly.cc
  poisson/CooSortBiliAssembly.cc
  poisson/CsrBiliAssembly.cc
  poisson/CsrGpuBiliAssembly.cc
  poisson/FemModule.cc
  poisson/FemModule.h
  poisson/LegacyBiliAssembly.cc
  poisson/NodeWiseCsrBiliAssembly.cc
Labels: reorg

#130 [Feat] manufactured solutions via External fuctions c#
  fourier/CMakeLists.txt
  fourier/ExternalFunctions.cs
  fourier/Fem.axl
  fourier/FemModule.cc
  fourier/Test.manufacture.solution.arc
Labels: enhancement

#131 [CI] Always run the workflow 'tests' and upgrade actions to v4
  .github/workflows/tests.yml
Labels: CI

#132 Add support to check result with multiple values
  elasticity/CMakeLists.txt
  elasticity/Fem.axl
  elasticity/FemModule.cc
  elasticity/Test.Elasticity.arc
  elasticity/tests/test_elasticity_results.txt
  femutils/FemUtils.cc
  femutils/FemUtils.h
Labels: enhancement
