Repository arcaneframework/arcanefem, pull requests merged in 2025-08, with the labels that each got.

#273 Dev/mab hex quad support aerodynamics
  femutils/ArcaneFemFunctions.h
  meshes/msh/aerodynamics_3d_coarse.hexa.msh
  modules/aerodynamics/CMakeLists.txt
  modules/aerodynamics/ElementMatrixHexQuad.h
  modules/aerodynamics/Fem.axl
  modules/aerodynamics/FemModule.cc
  modules/aerodynamics/FemModule.h
  modules/aerodynamics/check/test_2d.quad.txt
  modules/aerodynamics/check/test_3d.hexa.txt
  modules/aerodynamics/inputs/Joukowski.quad.arc
  modules/aerodynamics/inputs/Joukowski_3d.hexa.arc
Labels: novelty

#276 [feat] quad4/hex8 support acoustics
  femutils/ArcaneFemFunctions.h
  meshes/med/sphere_in_sphere.py
  meshes/med/truncated_cube.py
  meshes/msh/sphere_in_sphere.hexa.msh
  meshes/msh/sub.quad.msh
  modules/acoustics/CMakeLists.txt
  modules/acoustics/ElementMatrixHexQuad.h
  modules/acoustics/Fem.axl
  modules/acoustics/FemModule.cc
  modules/acoustics/FemModule.h
  modules/acoustics/check/sphere_3d.hexa.txt
  modules/acoustics/check/sub_2D.quad.txt
  modules/acoustics/inputs/3d_sphere_in_sphere.hexa.arc
  modules/acoustics/inputs/sub.quad.arc
Labels: novelty

#278 Move `CSRFormatView` in its own file
  femutils/CMakeLists.txt
  femutils/CsrFormatMatrixView.cc
  femutils/CsrFormatMatrixView.h
  femutils/DoFLinearSystem.h
Labels: refactor

#281 Make a base class `CsrDoFLinearSystemImpl` for implementation of `IDoFLinearSystemImpl` using CSR matrix format
  femutils/CMakeLists.txt
  femutils/CsrDoFLinearSystemImpl.cc
  femutils/CsrDoFLinearSystemImpl.h
  femutils/HypreDoFLinearSystem.cc
Labels: refactor

#283 [bug] in RHS node-field integral
  femutils/ArcaneFemFunctions.h
  modules/heat/FemModule.cc
  modules/heat/check/2d_conduction.txt
  modules/heat/check/2d_conduction_convection.txt
  modules/heat/check/2d_conduction_neumann_pointBC.txt
  modules/heat/check/3d_conduction.txt
  modules/heat/check/3d_conduction_convection_pointBC.txt
Labels: bug

#286 refactor dirichlet
  femutils/ArcaneFemFunctions.h
  femutils/ArcaneFemFunctionsGpu.h
  modules/acoustics/FemModule.cc
  modules/aerodynamics/FemModule.cc
  modules/elasticity/BodyForce.h
  modules/elasticity/CMakeLists.txt
  modules/elasticity/Dirichlet.h
  modules/elasticity/Fem.axl
  modules/elasticity/FemModule.cc
  modules/elasticity/FemModule.h
  modules/elasticity/Traction.h
  modules/elasticity/inputs/2D.dirichlet.bodyforce.quad.arc
  modules/elasticity/inputs/2D.dirichlet.traction.bodyforce.quad.arc
  modules/elasticity/inputs/3D.dirichlet.bodyforce.hexa.arc
  modules/elasticity/inputs/3D.dirichlet.traction.bodyforce.hexa.arc
  modules/elasticity/inputs/bar.2D.PointDirichlet.arc
  modules/elasticity/inputs/bar.2D.arc
  modules/elasticity/inputs/bar.2D.quad.arc
  modules/elasticity/inputs/bar.2D.traction.arc
  modules/elasticity/inputs/bar.2D.traction.bodyforce.arc
  modules/elasticity/inputs/bar.2D.traction.bodyforce.quad.arc
  modules/elasticity/inputs/bar.3D.Dirichlet.bodyForce.arc
  modules/elasticity/inputs/bar.3D.Dirichlet.traction.bodyForce.arc
  modules/elasticity/inputs/bar.3D.sphere.Dirichlet.bodyForce.arc
  modules/electrostatics/FemModule.cc
  modules/fourier/FemModule.cc
  modules/heat/FemModule.cc
  modules/laplace/FemModule.cc
  modules/poisson/FemModule.cc
Labels: refactor

#288 refactor Dirichlet/Source-Term/Traction
  femutils/ArcaneFemFunctions.h
  femutils/ArcaneFemFunctionsGpu.h
  modules/elastodynamics/CMakeLists.txt
  modules/elastodynamics/Dirichlet.h
  modules/elastodynamics/Fem.axl
  modules/elastodynamics/FemModule.cc
  modules/elastodynamics/FemModule.h
  modules/elastodynamics/SourceTerm.h
  modules/elastodynamics/Traction.h
  modules/elastodynamics/check/truncated-cube_point-bc.txt
  modules/elastodynamics/inputs/bar.3D.arc
  modules/elastodynamics/inputs/bar.3D.transient-traction.arc
  modules/elastodynamics/inputs/bar.Galpha.arc
  modules/elastodynamics/inputs/bar.arc
  modules/elastodynamics/inputs/bar.damping.arc
  modules/elastodynamics/inputs/bar.dirichlet.traction.bodyforce.arc
  modules/elastodynamics/inputs/bar.transient-traction.arc
  modules/elastodynamics/inputs/semi-circle.pointBC.arc
  modules/elastodynamics/inputs/truncated-cube.pointBC.arc
  modules/electrostatics/inputs/spheres.arc
  modules/electrostatics/inputs/truncated_cube.arc
  modules/electrostatics/inputs/truncated_cube.hexa.arc
  modules/heat/FemModule.cc
Labels: refactor

#290 Hex Quad support Elastodynamics
  meshes/msh/bar.six_quads.msh
  meshes/msh/bar.two_trias.msh
  modules/elastodynamics/CMakeLists.txt
  modules/elastodynamics/ElementMatrixHexQuad.h
  modules/elastodynamics/Fem.axl
  modules/elastodynamics/FemModule.cc
  modules/elastodynamics/FemModule.h
  modules/elastodynamics/SourceTerm.h
  modules/elastodynamics/Traction.h
  modules/elastodynamics/check/bar.quad.txt
  modules/elastodynamics/check/bar_2d_dirichlet-traction.quad.txt
  modules/elastodynamics/check/bar_3d.hexa.txt
  modules/elastodynamics/check/bar_3d_dirichlet-traction.hexa.txt
  modules/elastodynamics/inputs/bar.3D.dirichlet-traction.hexa.arc
  modules/elastodynamics/inputs/bar.3D.hexa.arc
  modules/elastodynamics/inputs/bar.dirichlet-traction.quad.arc
  modules/elastodynamics/inputs/bar.quad.arc
Labels: novelty

#293 refactor soildynamics
  modules/soildynamics/FemModule.cc
  modules/soildynamics/FemModule.h
  modules/soildynamics/SourceTerm.h
Labels: refactor
