Repository arcaneframework/arcanefem, pull requests merged in 2025-09, with the labels that each got.

#295 [femutils] Add helper classes to handle matrix row elimination and row column elimination
  femutils/ArcaneFemFunctions.h
  femutils/ArcaneFemFunctionsGpu.h
  femutils/DoFLinearSystem.cc
  femutils/DoFLinearSystem.h
  modules/bilaplacian/FemModule.cc
  modules/passmo/ElastodynamicModule.cc
  modules/passmonl/NLDynamicModule.cc
Labels: refactor

#298 [femutils] Add a base class `DoFLinearSystemImplBase` for common implementation de `IDoFLinearSystemImp`
  femutils/AlephDoFLinearSystem.cc
  femutils/CMakeLists.txt
  femutils/CsrDoFLinearSystemImpl.cc
  femutils/DoFLinearSystemImplBase.cc
  femutils/internal/CsrDoFLinearSystemImpl.h
  femutils/internal/DoFLinearSystemImplBase.h
Labels: refactor

#299 [femutils] Remove aleph implementation without value map
  femutils/AlephDoFLinearSystem.cc
Labels: refactor, minor

#301 Add a workflow to compile and test all modules when pushing to femutils
  .github/workflows/femutils.yml
Labels: CI

#302 [femutils] Fix a strange SEGV occuring in some configuration.
  femutils/AlephDoFLinearSystem.cc
Labels: bug

#303 [femtutils] Define the values of ELIMINATION(NONE|ROW|ROWCOLUMN) in only one place.
  femutils/ArcaneFemFunctionsGpu.cc
  femutils/DoFLinearSystemImplBase.cc
  femutils/FemUtilsGlobal.h
  femutils/internal/DoFLinearSystemImplBase.h
Labels: minor

#306 [bug] use unsigned int from Arcane
  modules/testlab/CooGpuBiliAssembly.cc
  modules/testlab/CooSortGpuBiliAssembly.cc
  modules/testlab/FemModule.h
  modules/testlab/NodeWiseCsrBiliAssembly.cc
Labels: bug

#309 Add prelimary support for RowColumn elimination when using CSR format
  femutils/ArcaneFemFunctionsGpu.cc
  femutils/ArcaneFemFunctionsGpu.h
  femutils/CsrDoFLinearSystemImpl.cc
  femutils/HypreDoFLinearSystem.cc
  femutils/internal/CsrDoFLinearSystemImpl.h
  femutils/internal/OrderedRowColumnMap.h
  modules/elasticity/CMakeLists.txt
  modules/elasticity/Fem.axl
  modules/elasticity/FemModule.cc
Labels: novelty

#310 [femutils] Minor refactoring of classes `BSRFormat` and `BSRMatrix`
  femutils/BSRFormat.cc
  femutils/BSRFormat.h
  femutils/CMakeLists.txt
  femutils/FemUtilsGlobal.h
  modules/testlab/CsrGpuBiliAssembly.cc
Labels: refactor

#311 [elasticy] Use GMRES for Hypre solver for RowColumn elimnination test.
  modules/elasticity/CMakeLists.txt
Labels: CI

#313 Separate Matrix and RHS transformation for `AlephDoFLinearSystemImpl` et `HypreDoFLinearSystemImpl`
  femutils/AlephDoFLinearSystem.cc
  femutils/CsrDoFLinearSystemImpl.cc
  femutils/HypreDoFLinearSystem.cc
  femutils/internal/CsrDoFLinearSystemImpl.h
Labels: refactor
