Repository arcaneframework/arcanefem, pull requests merged in 2025-03, with the labels that each got.

#226 [reorg] new way to impose dirichlet/neumann/bodyforce
  modules/elastodynamics/CMakeLists.txt
  modules/elastodynamics/Fem.axl
  modules/elastodynamics/FemModule.cc
  modules/elastodynamics/FemModule.h
  modules/elastodynamics/inputs/bar.Galpha.arc
  modules/elastodynamics/inputs/bar.arc
  modules/elastodynamics/inputs/bar.damping.arc
  modules/elastodynamics/inputs/bar.dirichlet.traction.bodyforce.arc
  modules/elastodynamics/inputs/bar.transient-traction.arc
  modules/elastodynamics/inputs/semi-circle.pointBC.arc
Labels: refactor, reorg

#229 [feat] Elastodynamics in 3D
  femutils/FemUtils.h
  modules/elastodynamics/CMakeLists.txt
  modules/elastodynamics/ElementMatrix.h
  modules/elastodynamics/FemModule.cc
  modules/elastodynamics/FemModule.h
  modules/elastodynamics/inputs/bar.3D.arc
  modules/elastodynamics/inputs/bar.3D.transient-traction.arc
Labels: enhancement

#230 [Refactor] ArcaneFem-Timer and PETSc flags
  femutils/ArcaneFemFunctions.h
  modules/acoustics/FemModule.cc
  modules/acoustics/FemModule.h
  modules/elasticity/FemModule.cc
  modules/elasticity/FemModule.h
  modules/elastodynamics/ElementMatrix.h
  modules/elastodynamics/FemModule.cc
  modules/elastodynamics/FemModule.h
  modules/fourier/FemModule.cc
  modules/fourier/FemModule.h
  modules/laplace/FemModule.cc
  modules/laplace/FemModule.h
  modules/poisson/FemModule.cc
  modules/poisson/FemModule.h
Labels: refactor

#233 Fixed the overflow with the new uid of DoF related to the arcane subdivider service
  femutils/FemDoFsOnNodes.cc
  modules/elasticity/CMakeLists.txt
Labels: enhancement, test

#234 [CI] remove md files from CI
  .github/workflows/acoustics.yml
  .github/workflows/aerodynamics.yml
  .github/workflows/bilaplacian.yml
  .github/workflows/elasticity.yml
  .github/workflows/elastodynamics.yml
  .github/workflows/electrostatics.yml
  .github/workflows/fourier.yml
  .github/workflows/heat.yml
  .github/workflows/passmo.yml
  .github/workflows/poisson.yml
  .github/workflows/soildynamics.yml
  .github/workflows/testlab.yml
  .github/workflows/tests.yml
Labels: CI

#239 [refactor] change logic for Dirchlet functions, clean up
  femutils/ArcaneFemFunctions.h
  meshes/msh/truncated_cube.geo
  meshes/msh/truncated_cube.msh
  modules/laplace/CMakeLists.txt
  modules/laplace/FemModule.cc
  modules/laplace/check/test_3D_truncated-cube.txt
  modules/laplace/inputs/L-shape.3D.dirichlet-neumann.arc
  modules/laplace/inputs/ring.dirichlet-neumann.arc
  modules/laplace/inputs/truncated-cube.3D.arc
Labels: refactor

#241 FixedMatrix -> RealMatrix
  doc/BSRFormat.md
  femutils/FemUtils.h
  modules/acoustics/FemModule.cc
  modules/acoustics/FemModule.h
  modules/aerodynamics/ElementMatrix.h
  modules/aerodynamics/FemModule.cc
  modules/aerodynamics/FemModule.h
  modules/bilaplacian/FemModule.cc
  modules/elasticity/ElementMatrix.h
  modules/elasticity/FemModule.h
  modules/elastodynamics/ElementMatrix.h
  modules/elastodynamics/FemModule.cc
  modules/elastodynamics/FemModule.h
  modules/electrostatics/FemModule.cc
  modules/electrostatics/FemModule.h
  modules/fourier/ElementMatrix.h
  modules/fourier/FemModule.cc
  modules/fourier/FemModule.h
  modules/heat/FemModule.cc
  modules/heat/FemModule.h
  modules/laplace/CMakeLists.txt
  modules/laplace/FemModule.cc
  modules/laplace/FemModule.h
  modules/passmo/ElastodynamicModule.cc
  modules/passmo/utilFEM.h
  modules/poisson/ElementMatrix.h
  modules/poisson/FemModule.cc
  modules/poisson/FemModule.h
  modules/soildynamics/ElementMatrix.h
  modules/soildynamics/FemModule.cc
  modules/soildynamics/FemModule.h
  modules/testlab/CooBiliAssembly.cc
  modules/testlab/CooSortBiliAssembly.cc
  modules/testlab/CsrBiliAssembly.cc
  modules/testlab/FemModule.cc
  modules/testlab/FemModule.h
  modules/testlab/LegacyBiliAssembly.cc
Labels: refactor

#245 [feat] laplace update gpu for RHS
  modules/laplace/CMakeLists.txt
  modules/laplace/ElementMatrix.h
  modules/laplace/FemModule.cc
  modules/laplace/FemModule.h
  modules/laplace/inputs/truncated-cube.neumann.3D.arc
Labels: enhancement
